m_player/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dhun.controller'))
] 

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dhun/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
# Create your models here.

class User(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    username=models.CharField(max_length=30,unique=True)
    password=models.CharField(max_length=30)

    def __str__(self):
        return f'username:{self.username}'

class Album(models.Model):
    userid=models.ForeignKey(User,on_delete=models.CASCADE)
    album_name=models.CharField(max_length=50)
    artist_name=models.CharField(max_length=50)
    album_logo=models.FileField()
    album_genre=models.CharField(max_length=50)

    def __str__(self):
        return f'album_name:{self.album_name}'
    def get_absolute_url(self):
        return reverse("dhun:home")

class Song(models.Model):
    album_id=models.ForeignKey(Album,on_delete=models.CASCADE)
    song_name=models.CharField(max_length=50)
    song_image=models.FileField()
    song=models.FileField()

    def __str__(self):
        return f'song_name:{self.song_name}, album_id:{self.album_id}'
    
    def get_absolute_url(self):
        return reverse("dhun:home")
    
# class Playlist(models.Model):
    
# class Recent(models.Model):
    
# class Favourite(models.Model):
    

dhun/controller.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name='dhun'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('signup/',views.Signupview.as_view(),name='signup'),
    path('login/',views.Signinview.as_view(),name='signin'),
    path('logout/',views.signout,name='signout'),
    path('myalbums/',views.Myalbum.as_view(),name='myalbum'),
    path('addalbum/',views.Addalbum.as_view(),name='addalbum'),
    path('addsong/',views.Addsong.as_view(),name='addsong'),
    path('playing/<int:pk>',views.Albumplaying.as_view(),name='play'),
    path('all_album/',views.Seeallalbum.as_view(),name='seeallalbum'),
    path('all_songs/',views.Seeallsong.as_view(),name='seeallsongs'),
    path('editsong/<int:pk>',views.Editsong.as_view(),name='editsong'),
    path('editalbum/<int:pk>',views.EditAlbum.as_view(),name='editalbum'),
    path('deletesong/<int:pk>',views.deletesong,name='deletesong'),
    

]

dhun/views.py
from pyexpat import model
from urllib import request
from django.contrib.auth.hashers import make_password
from django.forms import fields
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Album, Song, User
from .myforms import Signinform, Signupform 
from django.views import generic
from django.urls import reverse_lazy,reverse
from dhun import models
from django.contrib.auth.mixins import LoginRequiredMixin


class Signupview(generic.View):
    def get(self,request):
        return render(request,'dhun/signup.html',{'form':Signupform(None)})
    def post(self,request):
        f=Signupform(request.POST)
        if f.is_valid():
            tempform=f.save(commit=False)
            p=f.cleaned_data['password']
            tempform.password=make_password(p)
            tempform.save()
            return redirect('dhun:signin')
        return render(request,'dhun/signup.html',{'form':f})
        
class Signinview(generic.View):
    def get(self,request):
        return render(request,'dhun/login.html',{'form':Signinform(None)})
    def post(self,request):
        f=Signinform(request.POST)
        if f.is_valid():
            u=f.cleaned_data.get('username')
            obj=User.objects.get(username=u)
            self.request.session['user_log']={'username':obj.username}
            redirect_to =request.GET.get('next')
            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('dhun:home')
        return render(request,'dhun/login.html',{'form':f})
    
class Home(generic.ListView):
    template_name='dhun/home.html'
    context_object_name='data'
    def get_queryset(self):
        alb=Album.objects.all()
        songs=Song.objects.all()
        return {'songs':songs[:5], 'alb':alb[:5]}

def signout(request):
    request.session.pop("user_log")
    return redirect("dhun:home")

class Addalbum(LoginRequiredMixin,generic.CreateView):
    login_url='dhun:signin'
    model=Album
    template_name='dhun/addalbum.html'
    success_url=reverse_lazy('dhun:addsong')
    fields=['album_name','artist_name','album_logo','album_genre']
    context_object_name='form'
    def form_valid(self,form):
        u=self.request.session.get('user_log')
        u1=User.objects.get(username=u.get('username'))
        form.instance.userid=u1
        return super().form_valid(form)

class Addsong(generic.CreateView):
    model=Song
    template_name='dhun/addsong.html'
    fields=['album_id','song_name','song_image','song']
    context_object_name='form'

    # def get_success_url(self,request):
    #     redirect_to =request.GET.get('next')
    #     if redirect_to:
    #         return reverse(redirect_to)
    #     else:
    #         return reverse("dhun:home")    

class Myalbum(generic.ListView):
    template_name='dhun/myalbum.html'
    context_object_name='data'
    # model=Album
    def get_queryset(self):
        u=self.request.session.get("user_log")
        if u:
            alb1=User.objects.get(username=u.get('username'))
            return {'alb':Album.objects.filter(userid=alb1)}
        else:
            return None

class Albumplaying(generic.ListView):
    template_name='dhun/playing.html'
    context_object_name='data'
    def get_queryset(self):
        albumid=self.kwargs.get('pk')
        album=Album.objects.get(id=albumid)
        return {'album':album, 'song':album.song_set.all()}

class Seeallalbum(generic.ListView):
    template_name='dhun/seeallalbum.html'
    context_object_name='data'
    def get_queryset(self):
        dt=Album.objects.all()
        name='Albums'
        return {'dt':dt, 'name':name}

class Seeallsong(generic.ListView):
    template_name='dhun/seeallsong.html'
    context_object_name='data'
    def get_queryset(self):
        dt=Song.objects.all()
        name='Songs'
        return {'dt':dt, 'name':name}

class Editsong(generic.UpdateView):
    model=Song
    template_name='dhun/addsong.html'
    fields=['album_id','song_name','song_image','song']
    context_object_name='form'

class EditAlbum(generic.UpdateView):
    model=Album
    template_name='dhun/addalbum.html'
    fields=['userid','album_name','artist_name','album_logo','album_genre']
    context_object_name='form'
    
    

# class Deletesong(generic.DeleteView):
#     template_name='dhun/delete.html'
#     model=Song
#     # context_object_name='prod'
#     success_url=reverse_lazy('dhun:play')
#     success_message='product deleted'

def deletesong(request,pk):
    song=Song.objects.get(id=pk)
    song.delete()
    return redirect('dhun:play')

dhun/templates/dhun/addalbum.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Add New Album{% endblock %}
{% block body %}
<div class='main'>
<form method="post" enctype="multipart/form-data">
    <h3 style='text-align: center;'>Add Album</h3>
    {%csrf_token%}
    <table class="table table-bordered">
        {{form.as_table}}
    </table>
    <input type="submit" value="submit">

</form>
</div>
{% endblock body %}

dhun/templates/dhun/addsong.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Add New Song{% endblock %}
{% block body %}
<div class='main'>
<form method="post" enctype="multipart/form-data">
    <h3 style='text-align: center;'>Add Song</h3>
    {%csrf_token%}
    <table class="table table-bordered">
        {{form.as_table}}
    </table>
    <input type="submit" value="submit">

</form>
</div>
{% endblock body %}

dhun/templates/dhun/delete.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Deleting song{% endblock %}
{% block body %}

<h3>Do you want to delete this song</h3>
<input type='submit' value='submit'>

{% endblock %}

dhun/templates/dhun/home.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Home{% endblock %}
{% block body %}

<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">Albums</h3>
			<a href="{%url 'dhun:seeallalbum'%}">
			<span class="seeall">See all</span></a>
		  </div>
		  <br>
		<hr>
		{% for j in data.alb%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.album_logo.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.id%}" ><h5 class="card-title"><b>{{j.album_name}} by {{j.artist_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>
</div>
<br>

<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">Trending Songs</h3>
			<a href="{%url 'dhun:seeallsongs'%}">
			<span class="seeall">See all</span></a>
		  </div>
		  <br>
		<hr>
		{% for j in data.songs%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.album_id.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.song_image.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.album_id.id%}" ><h5 class="card-title"><b>{{j.song_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>
</div>
<br>

<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">New Songs</h3>
			<a href="{%url 'dhun:seeallsongs'%}">
			<span class="seeall">See all</span></a>
		  </div>
		  <br>
		<hr>
		{% for j in data.songs%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.album_id.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.song_image.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.album_id.id%}" ><h5 class="card-title"><b>{{j.song_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>

 
{% endblock body %}

dhun/templates/dhun/login.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<div class='main'>
<form method="post" enctype="multipart/form-data">
    <h3 style='text-align: center;'>Login</h3>
    {%csrf_token%}
    <table class="table table-bordered">
        {{form.as_table}}
    </table>
    <input type="submit" value="submit">

</form>
</div>
{% endblock body %}

dhun/templates/dhun/masterpage.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %} {%endblock%}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    .main form {
      background-color: darkgray;
      padding: 5px 24px;
      margin: 7% 20% 2% 20%;
      border: 10px;
      border-radius: 8px;
      box-shadow: 2px 2px 2px 2px black;
    }

    input[type="text"],
    input[type="password"],
    input[type="email"],
    input[type="number"],
    input[type="date"],
    select,
    textarea {
      width: 100%;
      padding: 5px;
      border: 1px solid #fff;
      border-radius: 4px;

    }

    input[type="submit"] {
      background-color: rgb(58, 56, 59);
      border-radius: 5px;
      border: none;
      width: 100%;
      padding: 12px 20px;
      color: white;
      font-size: large;

    }

    input[type="submit"]:hover {
      background-color: rgb(34, 66, 126);
    }

    .table,
    td,
    th,
    tr {
      border: 1px solid #fff;
    }

    .title .seeall {
      float: right;
      padding-right: 125px;

    }

    .title .headings {
      float: left;
      padding-right: 60px;
      padding-left: 75px;
      margin-top: -4px;
      margin-bottom: -13px;
    }

    .split {
      height: 100%;
      width: 50%;
      position: fixed;
      z-index: 1;
      top: 0;
      overflow-x: hidden;
      padding-top: 20px;
      margin-top: 3%;
    }

    .left {
      left: 0;
    }

    .right {
      right: 0;
    }

    .centered {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      text-align: center;
    }

    element.style {
      padding-left: 10px;
      padding-top: 10px;
      background-color: #459dfb;
    }

    .player {
      z-index: 10;
      background: #F9F9F9;
      color: #000;
      min-height: 80px;
      max-height: 150px;
      height: 110px;
      display: -webkit-box;
      display: flex;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      flex-direction: row;
    }
  </style>

</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'dhun:home'%}">DHUN</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'dhun:home'%}">Home</a></li>
        <!-- <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li> -->
      </ul>

      {% if "user_log" in request.session %}

      <ul class="nav navbar-nav">
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Add <span
              class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{%url 'dhun:addalbum'%}">Add New Album</a></li>
            <li><a href="{%url 'dhun:addsong'%}">Add New Song</a></li>
          </ul>
        </li>
        <li><a href="{%url 'dhun:myalbum'%}">My Albums</a></li> -->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{request.session.user_log.username}}</a></li>
        <li><a href="{% url 'dhun:signout'%}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>


      {%else%}

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'dhun:signup'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="{% url 'dhun:signin'%}?next={{request.path}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
      {%endif%}
    </div>
  </nav>


  {% block body%} {%endblock%}

</body>

</html>

dhun/templates/dhun/myalbum.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Myalbums{% endblock %}
{% block body %}


<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">Your Albums</h3>
			<a style="margin-top: -7px; margin-right: 17px; float: right;" href="{%url 'dhun:addalbum'%}" class="btn btn-primary">Add New Album</a>
		  </div>
		  <br>
		<hr>
		{% for j in data.alb%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.album_logo.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.id%}" ><h5 class="card-title"><b>{{j.album_name}} by {{j.artist_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>
</div>

{%endblock%}

dhun/templates/dhun/playing.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Playing {{data.album.album_name}}{% endblock %}
{% block body %}



<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="split left">
        <div class="centered">
          <img height="350" width="400" style="border-radius: 8px" src="{{data.album.album_logo.url}}">
          <h4><b>Album: </b>{{data.album.album_name}}</h4>
          <h4><b>Artist: </b>{{data.album.artist_name}}</h4>
          <p><b>Genre: </b> {{data.album.album_genre}}</p>
          {% if request.session.user_log.username == data.album.userid.username%}
      {%if 'user_log' in request.session%}
          <a style="margin-left: 90px; float: left;" href="{%url 'dhun:editalbum' data.album.id%}"
            class="btn btn-primary">Edit Album</a>
          <a style="margin-right: 93px; float: right;" href="#"
            class="btn btn-primary">Delete Album</a>
            {% endif %}
            {% endif %}
        </div>
      </div>
    </div>

    <div class="col-md-6" style="background: rgb(240, 239, 239); border: 10px; border-radius: 20px;">
      <h3>Queue</h3>
      {% if request.session.user_log.username == data.album.userid.username%}
      {%if 'user_log' in request.session%}<a style="margin-top: -60px; margin-left: 440px;"
        href="{%url 'dhun:addsong'%}?next={{request.path}}" class="btn btn-primary">Add Song</a>
      {% endif %}
      {% endif %}
      {%for i in data.song%}
      <div class="player" style="background-color:rgb(240, 239, 239) ;height:105px;">
        <div class="left"><img src="{{i.song_image.url}}" height="90" width="90" style="border-radius: 10px;"></div>
        <div class="right">
          <div>
            <a class="song"
              style=" margin-left: 7px; color: rgb(0, 0, 0); font-family:'Times New Roman', Times, serif; font-size: 18px;">{{i.song_name}}</a>
            {%if 'user_log' in request.session%}
            {% if request.session.user_log.username == data.album.userid.username%}

            <a href="{%url 'dhun:editsong' i.id%}?next={{request.path}}" class="btn btn-primary">Edit</a>
            <a href="{%url 'dhun:deletesong' i.id%}" class="btn btn-primary">Delete</a>
            {% endif %}
            {% endif %}
          </div>
          <audio controls="" name="media" src="{{i.song.url}}" type="audio/mpeg"></audio>

        </div>
      </div>

      {%endfor%}
    </div>

  </div>



  {%endblock%}

dhun/templates/dhun/seeallalbum.html
{% extends 'dhun/masterpage.html' %}
{% block title %}{{data.name}}{% endblock %}
{% block body %}


<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">{{data.name}}</h3>
			<a style="margin-top: -7px; margin-right: 17px; float: right;" href="{%url 'dhun:addalbum'%}" class="btn btn-primary">Add New Album</a>
			
		  </div>
		  <br>
		<hr>
		{% for j in data.dt%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.album_logo.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.id%}" ><h5 class="card-title"><b>{{j.album_name}} by {{j.artist_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>
</div>

{%endblock%}

dhun/templates/dhun/seeallsong.html
{% extends 'dhun/masterpage.html' %}
{% block title %}{{data.name}}{% endblock %}
{% block body %}


<div class="container-fluid">
	<div class="row mt-3">
	<div class="title">
			<h3 class="headings">{{data.name}}</h3>
			<a style="margin-top: -7px; margin-right: 17px; float: right;" href="{%url 'dhun:addsong'%}" class="btn btn-primary">Add New Song</a>
			
		  </div>
		  <br>
		<hr>
		{% for j in data.dt%}
		
		<div class="col-sm-3" style="padding-right: 60px; padding-left: 75px; width: 18%;">
			<div class="card" style="width: 18rem;">
				<a href="{%url 'dhun:play' j.id%}" ><img height="160" width="200" style="border-radius: 8px 8px 8px 8px;" src="{{j.song_image.url}}" class="card-img-top" alt="..."></a>
				<div class="card-body">
					<a href="{%url 'dhun:play' j.id%}" ><h5 class="card-title"><b>{{j.song_name}}</b></h5></a>
				</div>
			</div>
		</div> 
		{%endfor%}
	</div>
</div>
</div>

{%endblock%}

dhun/templates/dhun/signup.html
{% extends 'dhun/masterpage.html' %}
{% block title %}Signup{% endblock %}
{% block body %}
<div class='main'>
    
<form method="post" enctype="multipart/form-data">
    <h3 style='text-align: center;'>Signup Form</h3>
    {%csrf_token%}
    <table class="table table-bordered">
        {{form.as_table}}
    </table>
    <input type="submit" value="submit">

</form>
</div>
{% endblock body %}